name: indonesian_address_picker
description: Modern Indonesian address/region picker with province, city, district, and village data. Searchable, customizable, and offline-first.
version: 0.1.2
repository: https://github.com/donisettt/indonesian_address_picker
issue_tracker: https://github.com/donisettt/indonesian_address_picker/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.1.0  # Untuk download data

# Supaya JSON bisa di-load
flutter:
  assets:
    - lib/src/data/